### ISSUE TITLE
Documentation for including additional info in the custom reply

### ISSUE THREAD

**Issue by sayansil** [charliegerard/safe-space#9]
The github action works perfectly with my custom text reply, but I am not able to figure out a way to add additional information like the name of the person who made the toxic comment. How exactly should I go about this in my .yml file?

I have:

```yml
name: detox-messages
on: [issue_comment, pull_request_review]

jobs:
  toxic_check:
    runs-on: ubuntu-latest
    name: Toxicity check
    steps:
      - uses: actions/checkout@v2
      - name: Safe space - action step
        uses: charliegerard/safe-space@master
        with:
          GITHUB_TOKEN: ${{ secrets.DETOX_GITHUB_TOKEN }}
          message: "Hi <insert-name-here>. Please be kind on internet."
          toxicity_threshold: 0.7
```
